language: python

python:
#  - 2.7
#  - 3.4
#  - 3.5
  - 3.6
#  - pypy
#  - pypy3.5

install:
  - pip install tox twine wheel python-coveralls

script:
  - echo $TRAVIS_PYTHON_VERSION
  - export PYVER=`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1 | sed 's/^py//'`
  - echo $PYVER
  - tox -e py$PYVER


deploy:
  provider: pypi
  skip_cleanup: true
  user: $DEPLOY_USER
  pass: $DEPLOY_PASS
  on:
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
#jobs:
#  include:
#    - stage: package
#      python: 3.6
#      script:
#      - python setup.py bdist_wheel
#      - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS

after_success:
  - coveralls
