language: python
cache: pip
services:
  docker

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3.5

install:
  - pip install tox twine wheel python-coveralls

script:
  - export PYVER=`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1 | sed 's/^py//'`
  - python setup.py bdist_wheel
  - tox -e py$PYVER-lint --installpkg ./dist/*.whl
  - echo $TRAVIS_PYTHON_VERSION
  - '[ "$TRAVIS_PYTHON_VERSION" == "3.6" ] && tox -e py$PYVER-test --installpkg ./dist/*.whl || :'
  - '[ "$TRAVIS_PYTHON_VERSION" == "pypy3.5" ] && tox -e py$PYVER-test --installpkg ./dist/*.whl || :'

jobs:
  include:
    - stage: deploy-release
      python: 3.6
      script:
        - python setup.py bdist_wheel
        - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS true AND fork IS NOT true
    - stage: deploy-snapshot
      python: 3.6
      script:
        - python setup.py bdist_wheel
        - twine upload --repository-url https://test.pypi.org/legacy/
            dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS NOT true AND fork IS NOT true

after_success:
  - coveralls
